"""Knowledge Base domain entities — SQLModel tables for document and chunk storage."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import BigInteger, Column, DateTime, Index, Text
from sqlmodel import Field, SQLModel

# The six ``ix_kb_*`` / ``ix_emp_kb_*`` indexes below are all declared through
# ``__table_args__`` rather than ``Field(index=True)``. Their names predate the
# tables' current names — 078/079 created them as ``ix_kb_chunks_*`` while the
# tables are ``hr_knowledge_base_chunks`` — so ``index=True`` would render
# ``ix_hr_knowledge_base_chunks_document_id`` instead, and autogenerate would
# propose dropping the real index to create a differently-named twin.
#
# There is deliberately no index on either ``embedding`` column: the database
# has none (checked with ``pg_am`` — the schema holds zero non-btree indexes),
# so the model matching it is the correct state. Whether these tables *should*
# carry an ivfflat/hnsw index is a real performance question, but it is a new
# index on the database side, not model drift, and is out of this ticket.
#
# ``sa_type=Text`` below is load-bearing: a bare ``str`` renders SQLModel's
# ``AutoString``, i.e. ``VARCHAR`` with no length. That behaves exactly like
# ``TEXT`` but is a different type name, so autogenerate proposes an ALTER for
# every such column. The migrations wrote ``sa.Text()`` and the database has
# ``TEXT`` -- the model is the imprecise side. docs/schema-drift-audit.md 5.5.


class KnowledgeBaseDocument(SQLModel, table=True):
    """HR knowledge base document metadata.

    Tracks uploaded PDF/DOCX files and their ingestion status.
    The actual file bytes are stored in MinIO (bucket ``knowledge-base``).
    Chunks are stored in :class:`KnowledgeBaseChunk`.
    """

    __tablename__ = "hr_knowledge_base_documents"
    __table_args__ = (
        Index("ix_kb_documents_kb_type", "kb_type"),
        Index("ix_kb_documents_status", "status"),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    display_name: str = Field(max_length=500)
    category: str = Field(default="general", max_length=100)
    file_name: str = Field(max_length=500)
    storage_path: str = Field(max_length=1000)
    file_size: int = Field(sa_type=BigInteger)
    mime_type: str = Field(max_length=200)
    status: str = Field(
        default="pending",
        max_length=20,
    )
    error_message: str | None = Field(default=None, sa_type=Text)
    chunk_count: int = Field(default=0)
    description: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    kb_type: str = Field(default="hr", max_length=20)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


class KnowledgeBaseChunk(SQLModel, table=True):
    """A text chunk with its pgvector embedding for a knowledge base document.

    Each document is split into chunks of ~512 tokens (overlap 50).
    The ``embedding`` column stores a 1024-dimensional vector generated by
    the vroom-embedding service (AITeamVN/Vietnamese_Embedding_v2).
    """

    __tablename__ = "hr_knowledge_base_chunks"
    __table_args__ = (Index("ix_kb_chunks_document_id", "document_id"),)

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    document_id: uuid.UUID = Field(
        foreign_key="hr_knowledge_base_documents.id",
        ondelete="CASCADE",
    )
    chunk_index: int
    content: str = Field(sa_column=Column(Text, nullable=False))
    embedding: list[float] | None = Field(
        default=None,
        sa_column=Column(Vector(1024), nullable=True),
    )
    token_count: int = Field(default=0)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


class EmployeeKnowledgeBaseDocument(SQLModel, table=True):
    """Employee knowledge base document metadata.

    Tracks uploaded PDF/DOCX files and their ingestion status for the Employee KB.
    The actual file bytes are stored in MinIO (bucket ``knowledge-base``).
    Chunks are stored in :class:`EmployeeKnowledgeBaseChunk`.

    Physically separate from HR KB tables for security isolation (Issue #260).
    """

    __tablename__ = "employee_knowledge_base_documents"
    __table_args__ = (
        Index("ix_emp_kb_documents_kb_type", "kb_type"),
        Index("ix_emp_kb_documents_status", "status"),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    display_name: str = Field(max_length=500)
    category: str = Field(default="general", max_length=100)
    file_name: str = Field(max_length=500)
    storage_path: str = Field(max_length=1000)
    file_size: int = Field(sa_type=BigInteger)
    mime_type: str = Field(max_length=200)
    status: str = Field(
        default="pending",
        max_length=20,
    )
    error_message: str | None = Field(default=None, sa_type=Text)
    chunk_count: int = Field(default=0)
    description: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    kb_type: str = Field(default="employee", max_length=20)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


class EmployeeKnowledgeBaseChunk(SQLModel, table=True):
    """A text chunk with its pgvector embedding for an Employee KB document.

    Each document is split into chunks of ~512 tokens (overlap 50).
    The ``embedding`` column stores a 1024-dimensional vector generated by
    the vroom-embedding service (AITeamVN/Vietnamese_Embedding_v2).
    """

    __tablename__ = "employee_knowledge_base_chunks"
    __table_args__ = (Index("ix_emp_kb_chunks_document_id", "document_id"),)

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    document_id: uuid.UUID = Field(
        foreign_key="employee_knowledge_base_documents.id",
        ondelete="CASCADE",
    )
    chunk_index: int
    content: str = Field(sa_column=Column(Text, nullable=False))
    embedding: list[float] | None = Field(
        default=None,
        sa_column=Column(Vector(1024), nullable=True),
    )
    token_count: int = Field(default=0)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
